// <auto-generated />
namespace AdmCostoProduccion.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_20190912_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_20190912_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201909130255197_update_20190912_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
