//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmCostoProduccion.Common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdmCostoProduccion.Common.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Despachoes (DespachoId, Codigo, Fecha, Observacion, TipoDespachoId, AlmacenId, OrdenProduccionId, VentaId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@DespachoId, @Codigo, @Fecha, @Observacion, @TipoDespachoId, @AlmacenId, @OrdenProduccionId, @VentaId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string Despacho_Insert {
            get {
                return ResourceManager.GetString("Despacho_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Despachoes
        ///SET Codigo = @Codigo
        ///	, Fecha = @Fecha
        ///	, Observacion = @Observacion
        ///	, TipoDespachoId = @TipoDespachoId
        ///	, AlmacenId = @AlmacenId
        ///	, OrdenProduccionId = @OrdenProduccionId
        ///	, VentaId = @VentaId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE DespachoId = @DespachoId.
        /// </summary>
        public static string Despacho_Update {
            get {
                return ResourceManager.GetString("Despacho_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO DespachoDetalles (DespachoDetalleId, Cantidad, DespachoId, MercaderiaId, UnidadMedidaId, OrdenProduccionInsumoId, VentaDetalleId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@DespachoDetalleId, @Cantidad, @DespachoId, @MercaderiaId, @UnidadMedidaId, @OrdenProduccionInsumoId, @VentaDetalleId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string DespachoDetalle_Insert {
            get {
                return ResourceManager.GetString("DespachoDetalle_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE DespachoDetalles
        ///SET Cantidad = @Cantidad
        ///	, DespachoId = @DespachoId
        ///	, MercaderiaId = @MercaderiaId
        ///	, UnidadMedidaId = @UnidadMedidaId
        ///	, OrdenProduccionInsumoId = @OrdenProduccionInsumoId
        ///	, VentaDetalleId = @VentaDetalleId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE DespachoDetalleId = @DespachoDetalleId.
        /// </summary>
        public static string DespachoDetalle_Update {
            get {
                return ResourceManager.GetString("DespachoDetalle_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Kardexes (KardexId, CantidadSaldo, CantidadEntrada, CantidadSalida, OrdenServicioId, AlmacenId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@KardexId, @CantidadSaldo, @CantidadEntrada, @CantidadSalida, @OrdenServicioId, @AlmacenId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string Kardex_Insert {
            get {
                return ResourceManager.GetString("Kardex_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Kardexes
        ///SET CantidadSaldo = @CantidadSaldo
        ///	, CantidadEntrada = @CantidadEntrada
        ///	, CantidadSalida = @CantidadSalida
        ///	, OrdenServicioId = @OrdenServicioId
        ///	, AlmacenId = @AlmacenId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE KardexId = @KardexId.
        /// </summary>
        public static string Kardex_Update {
            get {
                return ResourceManager.GetString("Kardex_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO KardexMovimientoes (KardexMovimientoId, Fecha, Cantidad, KardexId, TipoMovimientoId, RecepcionDetalleId, DespachoDetalleId, MercaderiaId, UnidadMedidaId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@KardexMovimientoId, @Fecha, @Cantidad, @KardexId, @TipoMovimientoId, @RecepcionDetalleId, @DespachoDetalleId, @MercaderiaId, @UnidadMedidaId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string KardexMovimiento_Insert {
            get {
                return ResourceManager.GetString("KardexMovimiento_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE KardexMovimientoes
        ///SET Fecha = @Fecha
        ///	, Cantidad = @Cantidad
        ///	, KardexId = @KardexId
        ///	, TipoMovimientoId = @TipoMovimientoId
        ///	, RecepcionDetalleId = @RecepcionDetalleId
        ///	, DespachoDetalleId = @DespachoDetalleId
        ///	, MercaderiaId = @MercaderiaId
        ///	, UnidadMedidaId = @UnidadMedidaId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE KardexMovimientoId = @KardexMovimientoId.
        /// </summary>
        public static string KardexMovimiento_Update {
            get {
                return ResourceManager.GetString("KardexMovimiento_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO OrdenServicios (OrdenServicioId, CantidadSaldo, CantidadEntrada, CantidadSalida, MercaderiaId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@OrdenServicioId, @CantidadSaldo, @CantidadEntrada, @CantidadSalida, @MercaderiaId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string OrdenServicio_Insert {
            get {
                return ResourceManager.GetString("OrdenServicio_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE OrdenServicios
        ///SET CantidadSaldo = @CantidadSaldo
        ///	, CantidadEntrada = @CantidadEntrada
        ///	, CantidadSalida = @CantidadSalida
        ///	, MercaderiaId = @MercaderiaId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE OrdenServicioId = @OrdenServicioId.
        /// </summary>
        public static string OrdenServicio_Update {
            get {
                return ResourceManager.GetString("OrdenServicio_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Recepcions (RecepcionId, Codigo, Fecha, Observacion, TipoRecepcionId, AlmacenId, OrdenProduccionId, CompraId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@RecepcionId, @Codigo, @Fecha, @Observacion, @TipoRecepcionId, @AlmacenId, @OrdenProduccionId, @CompraId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string Recepcion_Insert {
            get {
                return ResourceManager.GetString("Recepcion_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Recepcions
        ///SET Codigo = @Codigo
        ///	, Observacion = @Observacion
        ///	, Fecha = @Fecha
        ///	, TipoRecepcionId = @TipoRecepcionId
        ///	, AlmacenId = @AlmacenId
        ///	, OrdenProduccionId = @OrdenProduccionId
        ///	, CompraId = @CompraId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE RecepcionId = @RecepcionId.
        /// </summary>
        public static string Recepcion_Update {
            get {
                return ResourceManager.GetString("Recepcion_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO RecepcionDetalles (RecepcionDetalleId, Cantidad, RecepcionId, MercaderiaId, UnidadMedidaId, OrdenProduccionInsumoId, CompraDetalleId, UsuarioCreacion, FechaCreacion, Eliminado)
        ///VALUES (@RecepcionDetalleId, @Cantidad, @RecepcionId, @MercaderiaId, @UnidadMedidaId, @OrdenProduccionInsumoId, @CompraDetalleId, @UsuarioCreacion, @FechaCreacion, @Eliminado).
        /// </summary>
        public static string RecepcionDetalle_Insert {
            get {
                return ResourceManager.GetString("RecepcionDetalle_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE RecepcionDetalles
        ///SET Cantidad = @Cantidad
        ///	, RecepcionId = @RecepcionId
        ///	, MercaderiaId = @MercaderiaId
        ///	, UnidadMedidaId = @UnidadMedidaId
        ///	, OrdenProduccionInsumoId = @OrdenProduccionInsumoId
        ///	, CompraDetalleId = @CompraDetalleId
        ///	, UsuarioUltimaActualizacion = @UsuarioUltimaActualizacion
        ///	, FechaUltimaActualizacion = @FechaUltimaActualizacion
        ///	, Eliminado = @Eliminado
        ///WHERE RecepcionDetalleId = @RecepcionDetalleId.
        /// </summary>
        public static string RecepcionDetalle_Update {
            get {
                return ResourceManager.GetString("RecepcionDetalle_Update", resourceCulture);
            }
        }
    }
}
